"""Assemble the output bundle (spec section 4).

Every successful generation produces a bundle, not a file. The reason is
`source.py`: a mesh is a dead end, but a parametric script plus its parameters
means the user can change a number and regenerate, open the STEP in real CAD, or
remix someone else's model. That is the thing a mesh-generation competitor
structurally cannot ship, and it is the reason a serious maker pays.

3MF is the default download and STL is the compatibility fallback, in that
order, for one concrete reason: the STL format has no unit declaration. Every
"my print came out 25.4 times too big" support ticket in this product category
traces back to that. 3MF states its units, so it cannot happen. The STL ships
with a README that says so in the first line.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

BUNDLE_FILES = {
    "3mf": "model.3mf",
    "stl": "model.stl",
    "step": "model.step",
    "source": "source.py",
    "params": "params.json",
    "report": "report.json",
    "slice": "slice_summary.json",
    "manifest": "manifest.json",
    "readme": "README.md",
}


@dataclass
class Bundle:
    """A written bundle on disk."""

    model_id: str
    directory: Path
    files: dict[str, str] = field(default_factory=dict)
    previews: dict[str, str] = field(default_factory=dict)

    def path(self, kind: str) -> Path | None:
        value = self.files.get(kind)
        return Path(value) if value else None

    def as_dict(self) -> dict:
        return {
            "model_id": self.model_id,
            "directory": str(self.directory),
            "files": self.files,
            "previews": self.previews,
        }

    def size_bytes(self) -> int:
        return sum(
            Path(p).stat().st_size for p in self.files.values() if Path(p).exists()
        )


def write_bundle(
    result,
    out_dir: Path | str,
    *,
    slice_summary: dict[str, Any] | None = None,
    template=None,
) -> Bundle:
    """Write a generation's artifacts into a directory.

    Copies rather than moves: the sandbox workdir is ephemeral and may be
    reclaimed, but the caller may still hold references to it for a retry or a
    second render.
    """
    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    bundle = Bundle(model_id=result.model_id, directory=directory)

    for kind, filename in (("stl", "model.stl"), ("3mf", "model.3mf"), ("step", "model.step")):
        source = result.artifacts.get(kind)
        if source and Path(source).exists():
            target = directory / filename
            shutil.copy2(source, target)
            bundle.files[kind] = str(target)

    if result.source_code:
        target = directory / BUNDLE_FILES["source"]
        target.write_text(_source_header(result, template) + result.source_code, encoding="utf-8")
        bundle.files["source"] = str(target)

    params_path = directory / BUNDLE_FILES["params"]
    params_path.write_text(
        json.dumps(_params_document(result, template), indent=2, sort_keys=True),
        encoding="utf-8",
    )
    bundle.files["params"] = str(params_path)

    if result.validation is not None:
        report_path = directory / BUNDLE_FILES["report"]
        report_path.write_text(json.dumps(result.validation, indent=2), encoding="utf-8")
        bundle.files["report"] = str(report_path)

    if slice_summary:
        slice_path = directory / BUNDLE_FILES["slice"]
        slice_path.write_text(json.dumps(slice_summary, indent=2), encoding="utf-8")
        bundle.files["slice"] = str(slice_path)

    previews_dir = directory / "previews"
    for name, source in (result.previews or {}).items():
        if not source or not Path(source).exists():
            continue
        previews_dir.mkdir(exist_ok=True)
        target = previews_dir / f"preview_{name}.png"
        shutil.copy2(source, target)
        bundle.previews[name] = str(target)

    readme_path = directory / BUNDLE_FILES["readme"]
    readme_path.write_text(_readme(result, bundle, template), encoding="utf-8")
    bundle.files["readme"] = str(readme_path)

    manifest_path = directory / BUNDLE_FILES["manifest"]
    manifest_path.write_text(
        json.dumps(_manifest(result, bundle, template), indent=2, sort_keys=True, default=str),
        encoding="utf-8",
    )
    bundle.files["manifest"] = str(manifest_path)

    return bundle


def _source_header(result, template) -> str:
    """A header that makes the script self-explanatory when opened alone.

    Someone who downloads this six months from now should be able to run it
    without finding the conversation that produced it.
    """
    lines = [
        '"""Generated by FormForge.',
        "",
        f"Request: {result.prompt}",
    ]
    if template is not None:
        lines.append(f"Template: {template.id} version {template.version}")
    lines += [
        "",
        "Every dimension below is a named constant in millimetres. Change one and",
        "re-run this file to regenerate the model:",
        "",
        "    pip install build123d",
        "    python source.py",
        "",
        "That produces the same solid this bundle was built from. To export it,",
        "add at the end:",
        "",
        "    from build123d import export_stl, export_step",
        "    export_stl(result, 'model.stl')",
        "    export_step(result, 'model.step')",
        '"""',
        "",
    ]
    return "\n".join(lines)


def _params_document(result, template) -> dict:
    """params.json: the values, plus enough schema to drive UI sliders."""
    document: dict[str, Any] = {
        "model_id": result.model_id,
        "values": result.params or {},
    }
    if template is not None:
        document["template_id"] = template.id
        document["template_version"] = template.version
        document["schema"] = template.param_schema
    elif getattr(result, "exposed_params", None):
        document["schema"] = {
            "type": "object",
            "properties": result.exposed_params,
        }
    return document


def _manifest(result, bundle: Bundle, template) -> dict:
    """The machine-readable index of the bundle."""
    return {
        "model_id": result.model_id,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "generator": "FormForge",
        "prompt": result.prompt,
        "intent": result.intent,
        "template_id": template.id if template else None,
        "template_version": template.version if template else None,
        "route": result.route,
        "language": result.language,
        "iterations": result.iterations,
        "units": "millimeter",
        "stats": {k: v for k, v in (result.stats or {}).items() if k != "brep_features"},
        "validation_passed": bool((result.validation or {}).get("passed")),
        "files": {k: Path(v).name for k, v in bundle.files.items()},
        "previews": {k: f"previews/{Path(v).name}" for k, v in bundle.previews.items()},
        "usage": result.usage.as_dict() if hasattr(result.usage, "as_dict") else {},
    }


def _readme(result, bundle: Bundle, template) -> str:
    """The human-readable README, leading with units."""
    stats = result.stats or {}
    bbox = stats.get("bbox_mm") or []
    size = " x ".join(f"{v:.1f}" for v in bbox) if bbox else "unknown"
    report = result.validation or {}
    summary = report.get("summary") or {}

    lines = [
        f"# {result.intent.get('subject') or 'FormForge model'}",
        "",
        "**All dimensions in this bundle are in millimetres.**",
        "",
        f"- Size: {size} mm",
        f"- Volume: {stats.get('volume_mm3', 0):.0f} mm3",
        f"- Triangles: {stats.get('triangles', 0)}",
    ]
    if template is not None:
        lines.append(f"- Template: `{template.id}` version {template.version}")
        if template.tested and template.tested.passed:
            lines.append(
                f"- Print tested: {template.tested.printer}, {template.tested.material}, "
                f"{template.tested.date}"
            )
    lines += ["", "## What to print", ""]

    if "3mf" in bundle.files:
        lines.append(
            "**Use `model.3mf`.** It declares its units, carries the recommended "
            "print settings, and every slicer reads it."
        )
    if "stl" in bundle.files:
        lines.append(
            "`model.stl` is provided for compatibility. STL has no way to record "
            "units, so if your slicer imports it at the wrong scale, the model is "
            "in millimetres -- set the import units to mm rather than scaling by "
            "25.4."
        )
    if "step" in bundle.files:
        lines.append(
            "`model.step` is the exact CAD solid. Open it in Fusion, FreeCAD, "
            "SolidWorks or Onshape to modify it properly -- it is not a mesh, so "
            "curves stay curves."
        )

    lines += [
        "",
        "## Changing it",
        "",
        "`source.py` is the script that built this model. Every dimension is a "
        "named constant at the top. Edit one, re-run the file, and you have a new "
        "model -- no CAD skills needed and nothing is baked in.",
        "",
        "`params.json` holds the same values in machine-readable form, with the "
        "valid range for each.",
        "",
        "## Printability",
        "",
    ]

    if report.get("passed"):
        lines.append(
            f"This model passed all {summary.get('checks', 0)} manufacturability "
            "checks for the profile it was generated against."
        )
    else:
        lines.append(
            f"This model has {summary.get('failures', 0)} unresolved "
            "manufacturability problem(s). See `report.json`."
        )
    warnings = report.get("warnings") or []
    if warnings:
        lines.append("")
        lines.append("Warnings worth knowing about before you print:")
        lines += [f"- {w.get('message', '')}" for w in warnings[:6]]

    lines += [
        "",
        "`report.json` has the full measurements: minimum wall thickness and "
        "where it is, overhang area, bridge spans, first-layer contact.",
        "",
    ]

    if "slice" in bundle.files:
        lines.append(
            "`slice_summary.json` has real print-time and filament estimates from "
            "a slicer, not a guess."
        )
        lines.append("")

    lines += [
        "---",
        "",
        "Generated by FormForge. The geometry was produced by a parametric CAD "
        "kernel, not a mesh generator, which is why the dimensions are exact and "
        "the solid is watertight by construction.",
    ]
    return "\n".join(lines)
